# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'option_download.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mhyt import yt_download
from text_error import Ui_error_text
import shutil

class Ui_Downloader(object):
    def setupUi(self, Downloader):
        Downloader.setObjectName("Downloader")
        Downloader.resize(369, 205)
        self.url_label = QtWidgets.QLabel(Downloader)
        self.url_label.setGeometry(QtCore.QRect(60, 40, 31, 16))
        self.url_label.setObjectName("url_label")
        self.url_text = QtWidgets.QLineEdit(Downloader)
        self.url_text.setGeometry(QtCore.QRect(90, 40, 191, 16))
        self.url_text.setObjectName("url_text")
        self.audio_button = QtWidgets.QRadioButton(Downloader)
        self.audio_button.setGeometry(QtCore.QRect(80, 110, 89, 20))
        self.audio_button.setObjectName("audio_button")
        self.video_button = QtWidgets.QRadioButton(Downloader)
        self.video_button.setGeometry(QtCore.QRect(180, 110, 89, 20))
        self.video_button.setObjectName("video_button")
        self.download_on = QtWidgets.QPushButton(Downloader)
        self.download_on.setGeometry(QtCore.QRect(190, 160, 75, 24))
        self.download_on.setObjectName("download_on")
        self.cancel_button = QtWidgets.QPushButton(Downloader)
        self.cancel_button.setGeometry(QtCore.QRect(80, 160, 75, 24))
        self.cancel_button.setObjectName("cancel_button")
        self.title_text = QtWidgets.QLineEdit(Downloader)
        self.title_text.setGeometry(QtCore.QRect(90, 70, 191, 16))
        self.title_text.setText("")
        self.title_text.setObjectName("title_text")
        self.title_label = QtWidgets.QLabel(Downloader)
        self.title_label.setGeometry(QtCore.QRect(60, 70, 31, 16))
        self.title_label.setObjectName("title_label")

        self.retranslateUi(Downloader)
        QtCore.QMetaObject.connectSlotsByName(Downloader)

    def retranslateUi(self, Downloader):
        _translate = QtCore.QCoreApplication.translate
        Downloader.setWindowTitle(_translate("Downloader", "downloader by Guilherme"))
        self.url_label.setText(_translate("Downloader", "URL:"))
        self.audio_button.setText(_translate("Downloader", "Audio"))
        self.video_button.setText(_translate("Downloader", "Video"))
        self.download_on.setText(_translate("Downloader", "Download"))
        self.cancel_button.setText(_translate("Downloader", "Cancelar"))
        self.title_label.setText(_translate("Downloader", "Title:"))
        #Butoon download
        self.download_on.clicked.connect(self.download_link)
        #Button exit program
        self.cancel_button.clicked.connect(lambda: self.exitScreen(Downloader))
        
    #Function download
    def download_link(self):
        url = self.url_text.text()
        title = self.title_text.text()
        if self.audio_button.isChecked() == True:
            try:    
                file_audio = title + '.mp3'               
                yt_download(url, file_audio, ismusic=True, codec = True)
            except:
                pass
            self.url_text.setText(" ")
            self.title_text.setText(" ")
        elif self.video_button.isChecked() == True:
            file_video = title + '.mp4'
            yt_download(url, file_video)
            self.url_text.setText(" ")
            self.title_text.setText(" ")
        else:
            self.error()
            
    #Function exit screen
    def exitScreen(self, Downloader):
        Downloader.exit()
 
    #On exit
    def error(self):
        self.error_text = QtWidgets.QWidget()
        self.ui = Ui_error_text()
        self.ui.setupUi(self.error_text)
        self.error_text.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Downloader = QtWidgets.QWidget()
    ui = Ui_Downloader()
    ui.setupUi(Downloader)
    Downloader.show()
    sys.exit(app.exec_())
