# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text_error.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error_text(object):
    def setupUi(self, error_text):
        error_text.setObjectName("error_text")
        error_text.resize(382, 133)
        self.text_error = QtWidgets.QTextBrowser(error_text)
        self.text_error.setGeometry(QtCore.QRect(60, 40, 251, 51))
        self.text_error.setObjectName("text_error")
        self.return_button = QtWidgets.QPushButton(error_text)
        self.return_button.setGeometry(QtCore.QRect(150, 100, 75, 24))
        self.return_button.setObjectName("return_button")

        self.retranslateUi(error_text)
        QtCore.QMetaObject.connectSlotsByName(error_text)

    def retranslateUi(self, error_text):
        _translate = QtCore.QCoreApplication.translate
        error_text.setWindowTitle(_translate("error_text", "Form"))
        self.text_error.setHtml(_translate("error_text", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Error \'Download failed\'</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Verify URL </span></p></body></html>"))
        self.return_button.setText(_translate("error_text", "Return"))
        #Button error_text screen action
        self.return_button.clicked.connect(lambda: self.error_textScreen(error_text))
        
    def error_textScreen(self, error_text):
        error_text.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    error_text = QtWidgets.QWidget()
    ui = Ui_error_text()
    ui.setupUi(error_text)
    error_text.show()
    sys.error_text(app.exec_())
